# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 24
      uses: actions/setup-java@v4
      with:
        java-version: '24'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    # This step uploads the compiled JAR file as an artifact.
    # The maven-assembly-plugin, configured in your pom.xml, creates a new JAR
    # with the '-jar-with-dependencies' suffix. This is the file that will be uploaded.
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        # The name of the artifact to be uploaded.
        name: ccp-assignment-jar
        # The path to the file to upload.
        # This will now target the correct file created by the assembly plugin.
        path: target/CCP-assignment-1.0-SNAPSHOT-jar-with-dependencies.jar
